Update Appium-CI.yml

diff --git a/.github/workflows/Appium-CI.yml b/.github/workflows/Appium-CI.yml
--- a/.github/workflows/Appium-CI.yml
+++ b/.github/workflows/Appium-CI.yml
@@ -32,8 +32,30 @@ jobs:
         echo no | avdmanager create avd -n test -k "system-images;android-23;google_apis;armeabi-v7a" --force
         cd ..
         emulator -avd test -no-window -no-boot-anim -no-audio -verbose &
-        echo "Waiting emulator is ready..."
-        echo "Emulator is ready!"
+        bootanim=""
+        failcounter=0
+        timeout_in_sec=360
+        until [[ "$bootanim" =~ "stopped" ]]; do
+        bootanim=`adb -e shell getprop init.svc.bootanim 2>&1 &`
+        if [[ "$bootanim" =~ "device not found" || "$bootanim" =~ "device offline"
+        || "$bootanim" =~ "running" ]]; then
+         let "failcounter += 1"
+        echo "Waiting for emulator to start"
+        if [[ $failcounter -gt timeout_in_sec ]]; then
+        echo "Timeout ($timeout_in_sec seconds) reached; failed to start emulator"
+        exit 1
+        fi
+        fi
+        sleep 1
+        done
+        echo "Emulator is ready"
+        # Unlock the Lock Screen
+        $ANDROID_HOME/platform-tools/adb shell input keyevent 82 &
+        $ANDROID_HOME/platform-tools/adb shell input keyevent 4 &
+        DURATION=$(( `date +%s` - START )) > /dev/null
+        echo "Android Emulator started after $DURATION seconds."
+        sleep 60
+
     - name: Run UI Tests
       run: chmod +x gradlew
     - name: Build with Gradle
